name: Java CI with Gradle

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test package
    - uses: actions/upload-artifact@v3
      with:
        name: gnode
        path: gnode/build/libs
    - uses: actions/upload-artifact@v3
      with:
        name: rest_api
        path: rest_api/build/libs
    - uses: actions/upload-artifact@v3
      with:
        name: quick_dirty
        path: quick_dirty/build/libs
